version: '3.7'

services:
  currency-exchange:
    image: kumarvijay2510/microservices-v3-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:800"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
     EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

  currency-conversion:
    image: kumarvijay2510/microservices-v3-currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:800"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

  naming-server:
    image: kumarvijay2510/microservices-v3-naming-server:0.0.1-SNAPSHOT
    mem_limit: 600m
    ports:
      - "8761:8761"
    networks:
      - currency-network
networks:
  currency-network:
